# Generated by Django 5.2.15 on 2026-07-02 17:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('unknown', 'Unknown'), ('worker', 'Worker'), ('customer', 'Customer')], default='unknown', max_length=20)),
                ('language', models.CharField(default='en', max_length=16)),
                ('messages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent session',
                'verbose_name_plural': 'agent sessions',
            },
        ),
    ]
